# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [11]:
planet = "Earth"
diameter = 12742

In [12]:
print("The diameter of {name} is {area} kilometers".format(name=planet ,area=diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [10]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [13]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
array1=np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
arr2=5*np.ones(10)
print(arr2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [16]:
Even_Integers=np.arange(20,35,2)
print(Even_Integers)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
X=np.arange(0,9).reshape(3,3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [18]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [19]:
import pandas as pd
import numpy as np


In [20]:
arr=np.arange(6).reshape(3,2)
df=pd.DataFrame(arr)
print(df)

   0  1
0  0  1
1  2  3
2  4  5


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [21]:
import pandas as pd
Date = pd.date_range(start ='1-1-2023',end ='10-01-2023', freq ='M')
print(Date)

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30'],
              dtype='datetime64[ns]', freq='M')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [22]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [23]:
import pandas as pd
arr= np.arraylists = lists
df=pd.DataFrame(arr)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
